-- Rename Term -> Course throughout, matching the app's terminology.
-- Hand-written (not autogenerated) so this RENAMEs in place instead of
-- dropping and recreating the tables — a generated diff for a model
-- rename would otherwise propose DROP TABLE "Term" + CREATE TABLE
-- "Course", destroying every row.

ALTER TABLE "Term" RENAME TO "Course";
ALTER TABLE "TermAssistant" RENAME TO "CourseAssistant";

ALTER TABLE "CourseAssistant" RENAME COLUMN "termId" TO "courseId";
ALTER TABLE "Enrollment" RENAME COLUMN "termId" TO "courseId";
ALTER TABLE "Session" RENAME COLUMN "termId" TO "courseId";
ALTER TABLE "Invite" RENAME COLUMN "termId" TO "courseId";

-- Constraint/index names follow Prisma's default naming convention
-- (<Table>_<col>_fkey, <Table>_pkey, <Table>_<cols>_key) so a future
-- `prisma migrate dev` sees no drift against these new names.
ALTER TABLE "Course" RENAME CONSTRAINT "Term_pkey" TO "Course_pkey";
ALTER TABLE "Course" RENAME CONSTRAINT "Term_subjectId_fkey" TO "Course_subjectId_fkey";
ALTER TABLE "Course" RENAME CONSTRAINT "Term_teacherId_fkey" TO "Course_teacherId_fkey";

ALTER TABLE "CourseAssistant" RENAME CONSTRAINT "TermAssistant_pkey" TO "CourseAssistant_pkey";
ALTER TABLE "CourseAssistant" RENAME CONSTRAINT "TermAssistant_termId_fkey" TO "CourseAssistant_courseId_fkey";
ALTER TABLE "CourseAssistant" RENAME CONSTRAINT "TermAssistant_userId_fkey" TO "CourseAssistant_userId_fkey";
ALTER INDEX "TermAssistant_termId_userId_key" RENAME TO "CourseAssistant_courseId_userId_key";

ALTER TABLE "Enrollment" RENAME CONSTRAINT "Enrollment_termId_fkey" TO "Enrollment_courseId_fkey";
ALTER INDEX "Enrollment_termId_studentId_key" RENAME TO "Enrollment_courseId_studentId_key";

ALTER TABLE "Session" RENAME CONSTRAINT "Session_termId_fkey" TO "Session_courseId_fkey";

ALTER TABLE "Invite" RENAME CONSTRAINT "Invite_termId_fkey" TO "Invite_courseId_fkey";

-- Recreate the enrollment-cap trigger's function body against the renamed
-- table/column (the trigger binding itself — name enforce_enrollment_cap /
-- enrollment_cap_trigger — never referenced "term", so it's untouched).
CREATE OR REPLACE FUNCTION enforce_enrollment_cap() RETURNS TRIGGER AS $$
DECLARE
  current_count INTEGER;
BEGIN
  -- Lock the parent Course row first so concurrent inserts for the same
  -- course serialize instead of both reading the count before either commits.
  PERFORM 1 FROM "Course" WHERE id = NEW."courseId" FOR UPDATE;
  SELECT COUNT(*) INTO current_count FROM "Enrollment" WHERE "courseId" = NEW."courseId";
  IF current_count >= 30 THEN
    RAISE EXCEPTION 'Course % already has 30 enrollments (max reached)', NEW."courseId"
      USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
